# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Order')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Ware')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.ShopCart')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Ware')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addr',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
