# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_userprofile_realname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
