# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_remove_userprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name='order summit time'),
        ),
    ]
