# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20160710_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='author',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ware',
            name='company',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
    ]
